### ISSUE TITLE
A.07.IR10.title.abstract

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-view-wms#89] opened 2016-03-23 10:38 UTC
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Coverage: This test case does not fully tests the IR10 requirement: 'An INSPIRE View service shall contain the INSPIRE metadata elements set out in the Metadata Regulation [INS MD] as shown in Table 3.'
# Proposed Change

Change the test or change the requirement only to cover keyword.
It may be better to merge this test case with A.04, A05, A07, and A11-A21.

**Comment by timrduffy** [comment] 2016-04-12 14:16
Confused as what the issue is here.  Elements that are mandatory (and conditional related to scenario 2 responses) are covered in other IR tests.  Only service title and abstract need to be tested in this IR 10 test.

Not sure if the test should be merged with any others

**Closed as completed** 2016-08-03 07:54 UTC
Labels: comm:ARE3NA, type:CT, sev:critical, type:CR, status:wontfix, res:rejected
